# Generated by Django 4.2.6 on 2023-10-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodInterno', models.IntegerField()),
                ('CodChamado', models.CharField(max_length=10)),
                ('DataCriacao', models.DateTimeField()),
                ('DataFinalizacao', models.DateTimeField()),
                ('SequenciaCategoria', models.CharField(max_length=50)),
                ('HoraFinalizacao', models.CharField(max_length=10)),
                ('TotalHorasAberturaFinalizacao', models.FloatField()),
                ('FirstCall', models.CharField(max_length=3)),
                ('ChaveOperador', models.IntegerField()),
                ('ChaveUsuario', models.IntegerField()),
                ('ChaveSla', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
