# Generated by Django 4.2.6 on 2023-10-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_chamado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
